/* tslint:disable */
/* eslint-disable */
/**
 * Tanner SSFF-OCR
 *  Backend Proyecto TANNER SSFF-OCR 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ConciliacionResponse,
    ConciliacionResponseFromJSON,
    ConciliacionResponseToJSON,
} from '../models/ConciliacionResponse';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError';

export interface ProcesarComprobanteRequest {
    imagen: Blob;
}

/**
 * 
 */
export class SistemaApi extends runtime.BaseAPI {

    /**
     * Creates request options for procesarComprobante without sending the request
     */
    async procesarComprobanteRequestOpts(requestParameters: ProcesarComprobanteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['imagen'] == null) {
            throw new runtime.RequiredError(
                'imagen',
                'Required parameter "imagen" was null or undefined when calling procesarComprobante().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['imagen'] != null) {
            formParams.append('imagen', requestParameters['imagen'] as any);
        }


        let urlPath = `/procesar-comprobante`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     * Procesar Comprobante
     */
    async procesarComprobanteRaw(requestParameters: ProcesarComprobanteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConciliacionResponse>> {
        const requestOptions = await this.procesarComprobanteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConciliacionResponseFromJSON(jsonValue));
    }

    /**
     * Procesar Comprobante
     */
    async procesarComprobante(requestParameters: ProcesarComprobanteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConciliacionResponse> {
        const response = await this.procesarComprobanteRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
