"""create requestcache table

Revision ID: 396195b87768
Revises: 
Create Date: 2026-06-16 22:51:02.325705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '396195b87768'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requestcache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('request_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('request_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('response_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tiempo_ms', sa.Integer(), nullable=False),
    sa.Column('tokens_input', sa.Integer(), nullable=False),
    sa.Column('tokens_thoughts', sa.Integer(), nullable=False),
    sa.Column('tokens_output', sa.Integer(), nullable=False),
    sa.Column('tokens_total', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('requestcache', schema=None) as batch_op:
        batch_op.create_index('uq_request_cache_model_hash', ['model', 'request_hash'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requestcache', schema=None) as batch_op:
        batch_op.drop_index('uq_request_cache_model_hash')

    op.drop_table('requestcache')
    # ### end Alembic commands ###
