/* tslint:disable */
/* eslint-disable */
/**
 * Tanner SSFF-OCR
 *  Backend Proyecto TANNER SSFF-OCR 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConciliacionResponse
 */
export interface ConciliacionResponse {
    /**
     * Fecha de la transferencia en formato YYYY-MM-DD.
     * @type {Date}
     * @memberof ConciliacionResponse
     */
    fecha?: Date | null;
    /**
     * Nombre de la persona que hace la transferencia.
     * @type {string}
     * @memberof ConciliacionResponse
     */
    nombre?: string | null;
    /**
     * RUT de la persona sin puntos y con guion para el digito verificador
     * @type {string}
     * @memberof ConciliacionResponse
     */
    rut?: string | null;
    /**
     * Monto de la transferencia, solo el número entero sin símbolos ni separadores
     * @type {number}
     * @memberof ConciliacionResponse
     */
    monto?: number | null;
}

/**
 * Check if a given object implements the ConciliacionResponse interface.
 */
export function instanceOfConciliacionResponse(value: object): value is ConciliacionResponse {
    return true;
}

export function ConciliacionResponseFromJSON(json: any): ConciliacionResponse {
    return ConciliacionResponseFromJSONTyped(json, false);
}

export function ConciliacionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConciliacionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'fecha': json['fecha'] == null ? undefined : (new Date(json['fecha'])),
        'nombre': json['nombre'] == null ? undefined : json['nombre'],
        'rut': json['rut'] == null ? undefined : json['rut'],
        'monto': json['monto'] == null ? undefined : json['monto'],
    };
}

export function ConciliacionResponseToJSON(json: any): ConciliacionResponse {
    return ConciliacionResponseToJSONTyped(json, false);
}

export function ConciliacionResponseToJSONTyped(value?: ConciliacionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fecha': value['fecha'] == null ? value['fecha'] : value['fecha'].toISOString().substring(0,10),
        'nombre': value['nombre'],
        'rut': value['rut'],
        'monto': value['monto'],
    };
}

